window.ALOJAMIENTOS = [
  {
    id: "Cabaña-tiempolibre",
    nombre: "Cabaña Tiempo Libre",
    tipo: "Cabañas • Naturaleza • Camping",
    direccion: "Coronel Francisco Loyola S/N",
    descripcion: "Cabaña dentro del camping, ideal para disfrutar en familia y refrescarse en la pileta.",
    telefono: "2664258650",
    whatsapp: "https://wa.me/5492664258650",
    mapa: "https://maps.app.goo.gl/Gf7eFpNvChMMvtD56",
    servicios: [
      "Wi-Fi",
      "Piscina",
      "Estacionamiento",
      "Parrilla",
      "Aire acondicionado",
      "Cancha de Voley Playero",
      "Proveeduria"
    ],
    fotos: [
      "media/alojamientos/tiempolibre/cabaña1.jpeg",
      "media/alojamientos/tiempolibre/cabaña2.jpeg",
      "media/alojamientos/tiempolibre/cabaña3.jpeg",
      "media/alojamientos/tiempolibre/cabaña4.jpeg",
      "media/alojamientos/tiempolibre/cabaña5.jpeg",
      "media/alojamientos/tiempolibre/cabaña6.jpeg",
      "media/alojamientos/tiempolibre/cabaña7.jpeg",
      "media/alojamientos/tiempolibre/cabaña8.jpeg",
      "media/alojamientos/tiempolibre/cabañ9.jpeg"
    ]
  },
  {
    id: "Dormis-tiempolibre",
    nombre: "Dormis Tiempo Libre",
    tipo: "Dormis • Naturaleza • Camping",
    direccion: "Coronel Francisco Loyola S/N",
    descripcion: "Dormis dentro del camping, ideal para disfrutar en familia y refrescarse en la pileta.",
    telefono: "2664258650",
    whatsapp: "https://wa.me/5492664258650",
    mapa: "https://maps.app.goo.gl/Gf7eFpNvChMMvtD56",
    servicios: [
      "Wi-Fi",
      "Piscina",
      "Estacionamiento",
      "Parrilla",
      "Aire acondicionado",
      "Cancha de Voley Playero",
      "Proveeduria"
    ],
    fotos: [
      "media/alojamientos/tiempolibre/dormis1.jpeg",
      "media/alojamientos/tiempolibre/dormis2.jpeg",
      "media/alojamientos/tiempolibre/dormis3.jpeg",
      "media/alojamientos/tiempolibre/dormis4.jpeg",
      "media/alojamientos/tiempolibre/dormis5.jpeg",
      "media/alojamientos/tiempolibre/dormis6.jpeg",
      "media/alojamientos/tiempolibre/dormis7.jpeg",
      "media/alojamientos/tiempolibre/dormis8.jpeg",
      "media/alojamientos/tiempolibre/dormis9.jpeg"
    ]
  },
  {
    id: "ruca-nanco",
    nombre: "Cabaña Ruca Nanco",
    tipo: "Cabañas",
    direccion: "Susana Swiky S/N",
    descripcion: "un lugar pensado para descansar y sentirte como en casa.",
    telefono: "2944620933",
    whatsapp: "https://wa.me/5492944620933",
    mapa: "https://maps.app.goo.gl/Y9mpV4MZ1VvrH2sP6",
    servicios: [
      "Wi-Fi",
      "Estacionamiento",
      "Parrilla",
      "Aire acondicionado"
    ],
    fotos: [
      "media/alojamientos/rucañanco/1.jpeg",
      "media/alojamientos/rucañanco/2.jpeg",
      "media/alojamientos/rucañanco/3.png",
      "media/alojamientos/rucañanco/4.png",
      "media/alojamientos/rucañanco/5.png",
      "media/alojamientos/rucañanco/6.png",
      "media/alojamientos/rucañanco/7.png"
    ]
  },
  {
    id: "cabaña-lascatitas",
    nombre: "Cabaña Las Catitas",
    tipo: "Cabañas • Naturaleza",
    direccion: "Las Heras 930",
    descripcion: "Ideal para compartir en familia y disfrutar del entorno natural.",
    telefono: "1144304022",
    whatsapp: "https://wa.me/5491144304022",
    mapa: "https://maps.app.goo.gl/5fMQAC7rQbipy8Lq6",
    servicios: [
      "Wi-Fi",
      "Piscina",
      "Estacionamiento",
      "Parrilla",
      "Aire acondicionado"
    ],
    fotos: [
      "media/alojamientos/lascatitas/1.jpeg",
      "media/alojamientos/lascatitas/2.jpeg",
      "media/alojamientos/lascatitas/3.jpeg",
      "media/alojamientos/lascatitas/4.jpeg",
      "media/alojamientos/lascatitas/5.jpeg",
      "media/alojamientos/lascatitas/6.jpeg",
      "media/alojamientos/lascatitas/7.jpeg",
      "media/alojamientos/lascatitas/8.jpeg",
      "media/alojamientos/lascatitas/9.jpeg",
      "media/alojamientos/lascatitas/10.jpeg"
    ]
  },
  {
    id: "alpina-posadas",
    nombre: "Cabaña Alpina - Posadas del Cielo",
    tipo: "Cabañas • Naturaleza • Parque",
    direccion: "Susana Swiky y Las Heras",
    descripcion: "Un refugio entre sierras y naturaleza para desconectar y disfrutar del aire libre. Nuestra Cabaña Alpina en Posada del Cielo combina confort, vistas al paisaje y todas las comodidades para que tu estadía sea relajante e inolvidable, con acceso a pileta, espacios verdes y actividades al aire libre.",
    telefono: "1144304022",
    whatsapp: "https://wa.me/5491144304022",
    mapa: "https://maps.app.goo.gl/hCkJKeikG4szQg87A",
    servicios: [
      "Wi-Fi",
      "Piscina",
      "Estacionamiento",
      "Parrilla",
      "Aire acondicionado",
      "Ropa de cama y aseo"
    ],
    fotos: [
      "media/alojamientos/posadas/alpina1.jpeg",
      "media/alojamientos/posadas/alpina2.png",
      "media/alojamientos/posadas/alpina3.jpg",
      "media/alojamientos/posadas/alpina4.jpg",
      "media/alojamientos/posadas/alpina5.jpg",
      "media/alojamientos/posadas/alpina6.jpg",
      "media/alojamientos/posadas/alpina7.jpg",
      "media/alojamientos/posadas/alpina8.jpg",
      "media/alojamientos/posadas/alpina9.jpg",
      "media/alojamientos/posadas/pileta.png",
      "media/alojamientos/posadas/pileta2.jpg"
    ]
  },
  {
    id: "suite-posadas",
    nombre: "Dormis Suite - Posadas del Cielo",
    tipo: "Cabañas • Naturaleza • Parque",
    direccion: "Susana Swiky y Las Heras",
    descripcion: "La Suite está pensada para quienes buscan una experiencia de descanso superior, combinando confort, privacidad y tranquilidad. Cuenta con un ambiente amplio y luminoso, cuidadosamente equipado para brindar una estadía placentera, ideal para parejas o escapadas especiales. Rodeada de naturaleza y con acceso a los espacios comunes del complejo, la Suite invita a relajarse y disfrutar de cada momento, ofreciendo un entorno cálido y acogedor donde el descanso es protagonista.",
    telefono: "1144304022",
    whatsapp: "https://wa.me/5491144304022",
    mapa: "https://maps.app.goo.gl/hCkJKeikG4szQg87A",
    servicios: [
      "Wi-Fi",
      "Piscina",
      "Estacionamiento",
      "Parrilla",
      "Aire acondicionado",
      "Ropa de cama y aseo"
    ],
    fotos: [
      "media/alojamientos/posadas/suite.jpg",
      "media/alojamientos/posadas/suite1.jpg",
      "media/alojamientos/posadas/suite2.jpg",
      "media/alojamientos/posadas/suite3.jpg",
      "media/alojamientos/posadas/suite4.jpg",
      "media/alojamientos/posadas/suite5.jpeg",
      "media/alojamientos/posadas/suite6.jpg",
      "media/alojamientos/posadas/suite7.jpeg",
      "media/alojamientos/posadas/suite8.jpeg",
      "media/alojamientos/posadas/suite9.jpeg",
      "media/alojamientos/posadas/suite10.jpeg",
      "media/alojamientos/posadas/pileta.png",
      "media/alojamientos/posadas/pileta2.jpg"
    ]
  },
  {
    id: "hotel-lujan",
    nombre: "Hotel Luján",
    tipo: "Hotel • Naturaleza • Parque",
    direccion: "Braulio Moyano S/N Camino al Dique",
    descripcion: "es atendido por sus propios dueños y cuenta con personal calificado que hacen que el servicio sea eficiente y más personalizado. El hotel cuenta con instalaciones totalmente equipadas y servicios especializados para garantizar el confort durante toda su estadía.",
    telefono: "2664649658",
    whatsapp: "https://wa.me/5492664649658",
    mapa: "https://maps.app.goo.gl/b3Jmq1fKc5bQ8caGA",
    servicios: [
      "Wi-Fi",
      "Piscina",
      "Estacionamiento",
      "Restaurante",
      "Aire acondicionado",
      "Salon de Juego",
      
    ],
    fotos: [
      "media/alojamientos/hotellujan/1.jpg",
      "media/alojamientos/hotellujan/2.jpg",
      "media/alojamientos/hotellujan/3.jpg",
      "media/alojamientos/hotellujan/4.jpg",
      "media/alojamientos/hotellujan/5.jpg",
      "media/alojamientos/hotellujan/6.jpg",
      "media/alojamientos/hotellujan/7.jpg",
      "media/alojamientos/hotellujan/8.jpg",
      "media/alojamientos/hotellujan/9.jpg",
      "media/alojamientos/hotellujan/10.jpg",
      "media/alojamientos/hotellujan/11.jpg",
      "media/alojamientos/hotellujan/12.jpg",
      "media/alojamientos/hotellujan/13.jpg",
      "media/alojamientos/hotellujan/14.jpg",
      "media/alojamientos/hotellujan/15.jpg",
      "media/alojamientos/hotellujan/16.jpg",
      "media/alojamientos/hotellujan/17.jpg",
      "media/alojamientos/hotellujan/18.jpg",
      "media/alojamientos/hotellujan/19.jpg",
      "media/alojamientos/hotellujan/20.jpg",
      "media/alojamientos/hotellujan/21.jpg",
      "media/alojamientos/hotellujan/22.jpg",
      "media/alojamientos/hotellujan/23.jpg",
      "media/alojamientos/hotellujan/24.jpg",
      "media/alojamientos/hotellujan/25.jpg",
      "media/alojamientos/hotellujan/26.jpg",
      "media/alojamientos/hotellujan/27.jpg",
      "media/alojamientos/hotellujan/28.jpg",
      "media/alojamientos/hotellujan/29.jpg",
      "media/alojamientos/hotellujan/30.jpg",
      "media/alojamientos/hotellujan/31.jpg",
      "media/alojamientos/hotellujan/32.jpg",
      "media/alojamientos/hotellujan/33.jpg",
      "media/alojamientos/hotellujan/34.jpg",
      "media/alojamientos/hotellujan/35.jpg",
      "media/alojamientos/hotellujan/36.jpg",
      "media/alojamientos/hotellujan/37.jpg"
    ]
  },
  {
    id: "smata",
    nombre: "Hosteria 17 de Octubre - Smata",
    tipo: "Hotel • Naturaleza • Parque",
    direccion: "Susana Swiky y Las Heras",
    descripcion: "La Hostería 17 de Octubre es un espacio ideal para descansar y disfrutar de la naturaleza en Luján, San Luis. Rodeada de paisajes serranos y aire puro, ofrece habitaciones cómodas y un ambiente cálido, perfecto para vacaciones, escapadas de fin de semana o estadías recreativas.",
    telefono: "1144304022",
    whatsapp: "https://wa.me/5491144304022",
    mapa: "https://maps.app.goo.gl/edAMLFBwfkgXd3Zy9",
    servicios: [
      "Wi-Fi",
      "Piscina",
      "Estacionamiento",
      "Restaurante",
      "Aire acondicionado"
    ],
    fotos: [
      "media/alojamientos/smata/1.jpg",
      "media/alojamientos/smata/2.jpg",
      "media/alojamientos/smata/3.jpg",
      "media/alojamientos/smata/4.jpg",
      "media/alojamientos/smata/5.jpg",
      "media/alojamientos/smata/6.jpg",
      "media/alojamientos/smata/7.jpg",
      "media/alojamientos/smata/8.jpg",
      "media/alojamientos/smata/9.jpg",
      "media/alojamientos/smata/10.jpg",
      "media/alojamientos/smata/11.jpg",
      "media/alojamientos/smata/12.jpg", 
      "media/alojamientos/smata/13.jpg",
      "media/alojamientos/smata/14.jpg",
      "media/alojamientos/smata/15.jpg",
      "media/alojamientos/smata/16.jpg",
      "media/alojamientos/smata/17.jpg",
      "media/alojamientos/smata/18.jpg",
      "media/alojamientos/smata/19.jpg",
      "media/alojamientos/smata/20.jpg",
      "media/alojamientos/smata/21.jpg",
      "media/alojamientos/smata/22.jpg",
      "media/alojamientos/smata/23.jpg",
      "media/alojamientos/smata/24.jpg",
      "media/alojamientos/smata/25.jpg",
      "media/alojamientos/smata/26.jpg"
    ]
  },
];
